-- installer.lua
-- FCS-10 / ATM-PCS :: Node bootstrap installer
--
-- Pulls the files needed to run a given node role onto a fresh CC:Tweaked
-- computer, straight from the GitHub repo's raw main branch. Every role
-- gets the shared lib/ files plus its own role-specific script. For every
-- role except test, a successful install also (re)writes /startup.lua so
-- the role's entry point auto-launches on every subsequent boot - see
-- AUTOBOOT_ROLES / writeStartupFile below.
--
-- Usage: installer install <supervisor|plc|hmi|rtu|test>

local BASE_URL = "https://raw.githubusercontent.com/Kabanosero/Minecraft-FCS-10/main/FCS-10/"

local COMMON_FILES = {
    "lib/config.lua",
    "lib/md5.lua",
    "lib/secnet.lua",
}

local ROLE_FILES = {
    supervisor = { "nodes/supervisor.lua" },
    plc        = { "nodes/plc.lua", "lib/rbac.lua" },
    hmi        = { "nodes/hmi.lua" },
    rtu        = { "nodes/rtu.lua" },
    test       = { "test/cmd_test.lua" },
}

-- Roles that get a generated /startup.lua auto-launching their entry point
-- (ROLE_FILES[role][1]) on every boot. `test` is intentionally excluded:
-- it's an interactive manual test harness (io.read() prompts a human at the
-- keyboard), not a long-running daemon, so auto-launching it on boot would
-- just leave an unattended computer hung at a keyboard prompt.
local AUTOBOOT_ROLES = {
    supervisor = true,
    plc        = true,
    hmi        = true,
    rtu        = true,
}

-- ---------------------------------------------------------------------------
-- Downloads a single repo-relative path into the matching local path,
-- creating any missing parent directory along the way. `onStatus`, if
-- given, is called as onStatus(path, status, detail) with status one of
-- "active"/"ok"/"failed" instead of this function printing directly - lets
-- the GUI wizard below drive a status table from the exact same download
-- logic the CLI path uses, rather than duplicating it. The CLI call site
-- never passes onStatus, so every print() here still fires exactly as
-- before for that path - behavior is unchanged for `installer install`.
-- ---------------------------------------------------------------------------
local function downloadFile(path, onStatus)
    if onStatus then
        onStatus(path, "active")
    end

    local url = BASE_URL .. path

    local response, err = http.get(url)
    if not response then
        if onStatus then
            onStatus(path, "failed", tostring(err))
        else
            print("[INSTALLER] FAILED: " .. path .. " (" .. tostring(err) .. ")")
        end
        return false
    end

    local contents = response.readAll()
    response.close()

    local dir = fs.getDir(path)
    if dir ~= "" and not fs.exists(dir) then
        fs.makeDir(dir)
    end

    local file, ferr = fs.open(path, "w")
    if not file then
        if onStatus then
            onStatus(path, "failed", tostring(ferr))
        else
            print("[INSTALLER] FAILED: could not open " .. path .. " for write (" .. tostring(ferr) .. ")")
        end
        return false
    end

    file.write(contents)
    file.close()

    if onStatus then
        onStatus(path, "ok")
    else
        print("[INSTALLER] OK: " .. path)
    end
    return true
end

-- ---------------------------------------------------------------------------
-- Writes /startup.lua so this role's entry point auto-launches on every
-- boot. CC:Tweaked automatically runs /startup.lua (if present) after each
-- computer boot/reboot, which is what lets a deployed node recover on its
-- own after a server restart or chunk reload instead of needing a human to
-- re-run it by hand. Always overwrites any existing /startup.lua: this
-- installer's own stated purpose is bootstrapping a FRESH computer (see
-- file header), and re-running install for a different role on the same
-- computer must correctly replace a stale reference to the old role.
-- ---------------------------------------------------------------------------
local function writeStartupFile(role, onStatus)
    local entryPath = ROLE_FILES[role][1]

    if onStatus then
        onStatus("/startup.lua", "active")
    end

    local content = "-- startup.lua\n"
        .. "-- Auto-generated by installer.lua for role '" .. role .. "'.\n"
        .. "-- Re-run \"installer install " .. role .. "\" to regenerate this file.\n"
        .. "dofile(\"/" .. entryPath .. "\")\n"

    local file, ferr = fs.open("/startup.lua", "w")
    if not file then
        if onStatus then
            onStatus("/startup.lua", "failed", tostring(ferr))
        else
            print("[INSTALLER] FAILED: could not write /startup.lua (" .. tostring(ferr) .. ")")
        end
        return false
    end

    file.write(content)
    file.close()

    if onStatus then
        onStatus("/startup.lua", "ok")
    else
        print("[INSTALLER] OK: /startup.lua (" .. role .. " will auto-launch on boot)")
    end
    return true
end

-- ---------------------------------------------------------------------------
-- Downloads every file for `role` (COMMON_FILES + ROLE_FILES[role]) and, for
-- an auto-boot role, writes /startup.lua once all downloads succeed. Shared
-- by both the CLI path (`installer install <role>`, onStatus omitted -
-- every print() above fires exactly as before) and the GUI wizard below
-- (onStatus drives an on-screen status table instead). Returns true only if
-- every download succeeded.
-- ---------------------------------------------------------------------------
local function installRole(role, onStatus)
    local allOk = true
    for _, path in ipairs(COMMON_FILES) do
        if not downloadFile(path, onStatus) then
            allOk = false
        end
    end
    for _, path in ipairs(ROLE_FILES[role]) do
        if not downloadFile(path, onStatus) then
            allOk = false
        end
    end

    if AUTOBOOT_ROLES[role] then
        if allOk then
            writeStartupFile(role, onStatus)
        else
            if onStatus then
                onStatus("/startup.lua", "skipped")
            else
                print("[INSTALLER] skipping /startup.lua: one or more downloads failed")
            end
        end
    end

    return allOk
end

local function printUsage()
    print("Usage:")
    print("  installer start")
    print("      Launch the click-driven install wizard.")
    print("  installer install <supervisor|plc|hmi|rtu|test>")
    print("      Headless install for scripting/automation.")
end

-- ===========================================================================
-- GUI wizard (installer start) - a click-driven role-select -> download ->
-- configure -> reboot flow, reusing nodes/hmi.lua's theme/button pattern.
--
-- SEQUENTIAL BLOCKING FLOW, not a unified event loop like hmi.lua: hmi.lua
-- must stay in one loop because it has two concurrent event sources to
-- service for its whole lifetime (mouse_click AND rednet_message - reactor
-- telemetry can arrive at any time). This wizard has no such concurrent
-- responsibility - it's a strictly linear, one-shot sequence where each
-- screen's only event source is its own mouse_click/read() wait, and the
-- next screen never needs to react to something that happened during a
-- previous one. Each screen function draws itself once, blocks until it has
-- a definitive result, and returns that result to runWizard() below.
-- ===========================================================================

local themes = {
    classic = {
        bg         = colors.lightGray,
        text       = colors.black,
        headerBg   = colors.gray,
        headerText = colors.white,
        btnDanger  = colors.red,
        btnSafe    = colors.green,
        btnNeutral = colors.lightBlue,
    },
    mono = {
        bg         = colors.black,
        text       = colors.white,
        headerBg   = colors.white,
        headerText = colors.black,
        btnDanger  = colors.white,
        btnSafe    = colors.lightGray,
        btnNeutral = colors.gray,
    },
}
local currentTheme = themes.classic

-- The 4 daemon roles only - `test` is an interactive dev harness, not a
-- deployable node (same reasoning as AUTOBOOT_ROLES's exclusion above), so
-- it stays reachable only via the CLI form. Order is deliberate/fixed
-- (not derived from AUTOBOOT_ROLES's pairs() order, which isn't guaranteed)
-- since it drives the role-select screen's button layout.
local GUI_ROLES = {
    { id = "supervisor", label = "SUPERVISOR" },
    { id = "plc",        label = "PLC" },
    { id = "hmi",        label = "HMI" },
    { id = "rtu",        label = "RTU" },
}

local function drawHeader(w, title)
    term.setBackgroundColor(currentTheme.headerBg)
    term.setTextColor(currentTheme.headerText)
    term.setCursorPos(1, 1)
    term.write(string.rep(" ", w))
    term.setCursorPos(2, 1)
    term.write(title)
end

local function drawButton(btn)
    term.setBackgroundColor(currentTheme[btn.colorKey])
    term.setTextColor(currentTheme.headerText)
    term.setCursorPos(btn.x, btn.y)
    term.write(string.rep(" ", btn.width))
    term.setCursorPos(btn.x + math.floor((btn.width - #btn.label) / 2), btn.y)
    term.write(btn.label)
end

local function hitTest(buttons, x, y)
    for _, btn in ipairs(buttons) do
        if y == btn.y and x >= btn.x and x < btn.x + btn.width then
            return btn
        end
    end
    return nil
end

-- Full clear + header + optional subtitle + button draw, once per screen
-- entry - matches hmi.lua's/supervisor.lua's "full redraw on entry, only
-- targeted updates after that" convention (see screenDownload's per-row
-- status updates below for the targeted-update half of that pattern).
local function drawScreen(w, h, title, subtitle, buttons)
    term.setBackgroundColor(currentTheme.bg)
    term.setTextColor(currentTheme.text)
    term.clear()

    drawHeader(w, title)

    if subtitle then
        term.setCursorPos(2, 3)
        term.write(subtitle)
    end

    for _, btn in ipairs(buttons) do
        drawButton(btn)
    end
end

-- Restores default shell colors/cursor state. Only needed on the one
-- non-reboot exit path (screenDownload's EXIT button) - os.reboot() wipes
-- all runtime terminal state on every other path, so nothing else needs it.
local function resetTerm()
    term.setBackgroundColor(colors.black)
    term.setTextColor(colors.white)
    term.setCursorBlink(false)
    term.clear()
    term.setCursorPos(1, 1)
end

local function screenRoleSelect()
    local w, h = term.getSize()

    local btnWidth = math.max(10, math.min(w - 4, 24))
    local btnX = math.floor((w - btnWidth) / 2) + 1
    local spacing = 3
    if 4 + #GUI_ROLES * spacing > h then
        spacing = math.max(2, math.floor((h - 5) / #GUI_ROLES))
    end

    local buttons = {}
    for i, roleDef in ipairs(GUI_ROLES) do
        buttons[i] = {
            id = roleDef.id, label = roleDef.label,
            x = btnX, y = 3 + i * spacing, width = btnWidth,
            colorKey = "btnNeutral",
        }
    end

    drawScreen(w, h, "FCS-10 Installer", "Select node role to install:", buttons)

    while true do
        local _, button, x, y = os.pullEvent("mouse_click")
        if button == 1 then
            local btn = hitTest(buttons, x, y)
            if btn then
                return btn.id
            end
        end
    end
end

local STATUS_GLYPH = {
    pending = { text = "...",  colorKey = "text"       },
    active  = { text = ">>>",  colorKey = "btnNeutral"  },
    ok      = { text = "OK",   colorKey = "btnSafe"     },
    failed  = { text = "FAIL", colorKey = "btnDanger"   },
    skipped = { text = "SKIP", colorKey = "btnDanger"   },
}

local function screenDownload(role)
    local w, h = term.getSize()

    local files = {}
    for _, path in ipairs(COMMON_FILES) do
        files[#files + 1] = path
    end
    for _, path in ipairs(ROLE_FILES[role]) do
        files[#files + 1] = path
    end
    if AUTOBOOT_ROLES[role] then
        files[#files + 1] = "/startup.lua"
    end

    local rowOf = {}
    for i, path in ipairs(files) do
        rowOf[path] = i
    end

    local function drawRow(path, status)
        local row = rowOf[path]
        if not row or 2 + row > h then
            return
        end
        local glyph = STATUS_GLYPH[status] or STATUS_GLYPH.pending
        term.setBackgroundColor(currentTheme.bg)
        term.setCursorPos(2, 2 + row)
        term.setTextColor(currentTheme.text)
        local label = path
        if #label > w - 8 then
            label = label:sub(1, w - 8)
        end
        term.write(label .. string.rep(" ", math.max(0, w - 8 - #label)))
        term.setCursorPos(w - 5, 2 + row)
        term.setTextColor(currentTheme[glyph.colorKey] or currentTheme.text)
        term.write(string.format("%-5s", glyph.text))
    end

    drawScreen(w, h, "Installing: " .. role:upper(), nil, {})
    for _, path in ipairs(files) do
        drawRow(path, "pending")
    end

    while true do
        local allOk = installRole(role, drawRow)
        if allOk then
            return "ok"
        end

        local n = #files
        term.setBackgroundColor(currentTheme.bg)
        term.setTextColor(currentTheme.btnDanger)
        term.setCursorPos(2, 4 + n)
        term.write("One or more files failed to download.")
        term.setTextColor(currentTheme.text)

        local retryBtn = { id = "retry", label = "RETRY", x = 3,  y = 6 + n, width = 12, colorKey = "btnSafe" }
        local exitBtn  = { id = "exit",  label = "EXIT",  x = 17, y = 6 + n, width = 12, colorKey = "btnDanger" }
        drawButton(retryBtn)
        drawButton(exitBtn)

        local choice
        while not choice do
            local _, button, x, y = os.pullEvent("mouse_click")
            if button == 1 then
                local btn = hitTest({ retryBtn, exitBtn }, x, y)
                if btn then
                    choice = btn.id
                end
            end
        end

        if choice == "exit" then
            return "exit"
        end

        -- RETRY: reset every row to pending and loop back into installRole().
        for _, path in ipairs(files) do
            drawRow(path, "pending")
        end
        term.setBackgroundColor(currentTheme.bg)
        term.setCursorPos(2, 4 + n)
        term.write(string.rep(" ", w - 2))
        term.setCursorPos(3, 6 + n)
        term.write(string.rep(" ", 30))
    end
end

local function screenConfig()
    local w, h = term.getSize()

    drawScreen(w, h, "Network Secret Key", nil, {})
    term.setCursorPos(2, 3)
    term.write("Enter the network secret key for this site.")
    term.setCursorPos(2, 4)
    term.write("This is written to /secret.key on this computer.")
    term.setCursorPos(2, 5)
    term.write("Leave blank to keep the default DEV placeholder key")
    term.setCursorPos(2, 6)
    term.write("(NOT SECURE - change before production use).")

    term.setCursorPos(2, 8)
    term.write("Secret: ")
    term.setTextColor(currentTheme.text)
    term.setBackgroundColor(currentTheme.bg)
    term.setCursorBlink(true)
    local secret = read("*")
    term.setCursorBlink(false)

    if secret == nil or secret == "" then
        term.setCursorPos(2, 10)
        term.write("Using default DEV placeholder key.")
    else
        local file, ferr = fs.open("/secret.key", "w")
        if file then
            file.write(secret)
            file.close()
            term.setCursorPos(2, 10)
            term.write("/secret.key written.")
        else
            term.setCursorPos(2, 10)
            term.write("FAILED to write /secret.key: " .. tostring(ferr))
        end
    end
end

local function screenDone(role)
    local w, h = term.getSize()

    local rebootBtn = { id = "reboot", label = "REBOOT NOW", x = 3, y = 6, width = 16, colorKey = "btnSafe" }
    drawScreen(w, h, "Installation Complete", nil, { rebootBtn })

    term.setCursorPos(2, 3)
    term.write(role:upper() .. " has been installed.")
    term.setCursorPos(2, 4)
    term.write("It will launch automatically on every boot.")

    while true do
        local _, button, x, y = os.pullEvent("mouse_click")
        if button == 1 then
            local btn = hitTest({ rebootBtn }, x, y)
            if btn then
                term.setCursorPos(2, 8)
                term.write("Rebooting...")
                os.reboot()
            end
        end
    end
end

local function runWizard()
    local role = screenRoleSelect()
    local result = screenDownload(role)
    if result == "exit" then
        resetTerm()
        return
    end
    screenConfig()
    screenDone(role) -- never returns (os.reboot())
end

-- ---------------------------------------------------------------------------
-- Main
-- ---------------------------------------------------------------------------
local args = { ... }
local action = args[1]
local role = args[2]

if action == "install" and ROLE_FILES[role] then
    installRole(role)
elseif action == "start" then
    runWizard()
else
    printUsage()
end
