-- installer.lua
-- FCS-10 / ATM-PCS :: Node bootstrap installer
--
-- Pulls the files needed to run a given node role onto a fresh CC:Tweaked
-- computer, straight from the GitHub repo's raw main branch. Every role
-- gets the shared lib/ files plus its own role-specific script. For every
-- role except test, a successful install also (re)writes /startup.lua so
-- the role's entry point auto-launches on every subsequent boot - see
-- AUTOBOOT_ROLES / writeStartupFile below.
--
-- Usage: installer install <supervisor|plc|hmi|rtu|test>

local BASE_URL = "https://raw.githubusercontent.com/Kabanosero/Minecraft-FCS-10/main/FCS-10/"

local COMMON_FILES = {
    "lib/config.lua",
    "lib/md5.lua",
    "lib/secnet.lua",
}

local ROLE_FILES = {
    supervisor = { "nodes/supervisor.lua" },
    plc        = { "nodes/plc.lua" },
    hmi        = { "nodes/hmi.lua" },
    rtu        = { "nodes/rtu.lua" },
    test       = { "test/cmd_test.lua" },
}

-- Roles that get a generated /startup.lua auto-launching their entry point
-- (ROLE_FILES[role][1]) on every boot. `test` is intentionally excluded:
-- it's an interactive manual test harness (io.read() prompts a human at the
-- keyboard), not a long-running daemon, so auto-launching it on boot would
-- just leave an unattended computer hung at a keyboard prompt.
local AUTOBOOT_ROLES = {
    supervisor = true,
    plc        = true,
    hmi        = true,
    rtu        = true,
}

-- ---------------------------------------------------------------------------
-- Downloads a single repo-relative path into the matching local path,
-- creating any missing parent directory along the way.
-- ---------------------------------------------------------------------------
local function downloadFile(path)
    local url = BASE_URL .. path

    local response, err = http.get(url)
    if not response then
        print("[INSTALLER] FAILED: " .. path .. " (" .. tostring(err) .. ")")
        return false
    end

    local contents = response.readAll()
    response.close()

    local dir = fs.getDir(path)
    if dir ~= "" and not fs.exists(dir) then
        fs.makeDir(dir)
    end

    local file, ferr = fs.open(path, "w")
    if not file then
        print("[INSTALLER] FAILED: could not open " .. path .. " for write (" .. tostring(ferr) .. ")")
        return false
    end

    file.write(contents)
    file.close()

    print("[INSTALLER] OK: " .. path)
    return true
end

-- ---------------------------------------------------------------------------
-- Writes /startup.lua so this role's entry point auto-launches on every
-- boot. CC:Tweaked automatically runs /startup.lua (if present) after each
-- computer boot/reboot, which is what lets a deployed node recover on its
-- own after a server restart or chunk reload instead of needing a human to
-- re-run it by hand. Always overwrites any existing /startup.lua: this
-- installer's own stated purpose is bootstrapping a FRESH computer (see
-- file header), and re-running install for a different role on the same
-- computer must correctly replace a stale reference to the old role.
-- ---------------------------------------------------------------------------
local function writeStartupFile(role)
    local entryPath = ROLE_FILES[role][1]

    local content = "-- startup.lua\n"
        .. "-- Auto-generated by installer.lua for role '" .. role .. "'.\n"
        .. "-- Re-run \"installer install " .. role .. "\" to regenerate this file.\n"
        .. "dofile(\"/" .. entryPath .. "\")\n"

    local file, ferr = fs.open("/startup.lua", "w")
    if not file then
        print("[INSTALLER] FAILED: could not write /startup.lua (" .. tostring(ferr) .. ")")
        return false
    end

    file.write(content)
    file.close()

    print("[INSTALLER] OK: /startup.lua (" .. role .. " will auto-launch on boot)")
    return true
end

local function printUsage()
    print("Usage: installer install <supervisor|plc|hmi|rtu|test>")
end

-- ---------------------------------------------------------------------------
-- Main
-- ---------------------------------------------------------------------------
local args = { ... }
local action = args[1]
local role = args[2]

if action == "install" and ROLE_FILES[role] then
    local allOk = true
    for _, path in ipairs(COMMON_FILES) do
        if not downloadFile(path) then
            allOk = false
        end
    end
    for _, path in ipairs(ROLE_FILES[role]) do
        if not downloadFile(path) then
            allOk = false
        end
    end

    if AUTOBOOT_ROLES[role] then
        if allOk then
            writeStartupFile(role)
        else
            print("[INSTALLER] skipping /startup.lua: one or more downloads failed")
        end
    end
else
    printUsage()
end
